name: Java CI Multi-LTS

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 11, 17, 21]

    name: Build & Test (Java ${{ matrix.java-version }})

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Run ISW2 Tests
        #   Execute just the -isw2 tests
        run: |
          mvn clean install -Dcheckstyle.skip -Dspotbugs.skip -DskipTests
          mvn test -pl openjpa-kernel -Dtest=Isw2* -Dcheckstyle.skip -Dspotbugs.skip
