
name: Main CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      # Prima compiliamo tutti i moduli necessari tranne xmlstore
      - name: Build moduli base
        run: >
          mvn clean install 
          -pl '!openjpa-xmlstore,!openjpa-slice,!openjpa-examples,!openjpa-integration' 
          -DskipTests 
          -Dcheckstyle.skip=true

      # Poi compiliamo xmlstore separatamente
      - name: Build xmlstore
        run: >
          mvn install 
          -pl openjpa-xmlstore 
          -am 
          -DskipTests 
          -Dcheckstyle.skip=true

      # Infine eseguiamo solo i test che ci interessano
      - name: Test PersistenceProviderImpl
        run: >
          mvn test 
          -pl openjpa-persistence 
          -Dtest=PersistenceProviderImplJUnit5Tests