
name: Main CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - name: 'Cache Maven packages'
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: 'cache'
          restore-keys: 'cache'
      - name: 'Build with Maven'
        run: mvn -B install --file pom.xml
      - name: 'Remove Snapshots Before Caching'
        run: find ~/.m2 -name '*SNAPSHOT' | xargs rm -Rf






      # Infine compiliamo xmlstore disabilitando esplicitamente l'enhancement
      - name: Build modulo xmlstore con test
        run: >
          mvn clean install 
          -pl openjpa-xmlstore 
          -am 
          -DargLine="-javaagent:~/.m2/repository/org/apache/openjpa/openjpa/4.1.2-SNAPSHOT/openjpa-4.1.2-SNAPSHOT.jar" 
          -Dcheckstyle.skip=true 
          -Dmaven.test.skip=true
      
      
      
      

      # Prima compiliamo i moduli core necessari
      - name: Build moduli base
        run: >
          mvn clean install 
            -pl '!openjpa-xmlstore' 
            -Dcheckstyle.skip=true 
            -Dmaven.test.skip=true
      

      # Eseguiamo i test specifici
      - name: Test PersistenceProviderImpl
        run: >
          mvn test 
          -pl openjpa-persistence 
          -Dtest=PersistenceProviderImplJUnit5Tests 
          -Dskip.enhancer=true 
          -P!test-enhance

     


