
name: Main CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Build modulo xmlstore con test
        run: >
          mvn clean install 
          -pl openjpa-xmlstore 
          -am 
          -Drat.skip=true 
          -Dcheckstyle.skip=true 
          -Dopenjpa.DynamicEnhancementAgent=false

      - name: Build progetto completo (senza test, escludendo xmlstore)
        run: >
          mvn clean install 
          -DskipTests 
          -DskipITs 
          -Drat.skip=true 
          -Dcheckstyle.skip=true 
          -Dopenjpa.DynamicEnhancementAgent=false 
          -pl '!openjpa-xmlstore'

      - name: Esegui test su openjpa-persistence
        run: >
          mvn test 
          -pl openjpa-persistence 
          -am 
          -Drat.skip=true 
          -Dcheckstyle.skip=true 
          -Dopenjpa.DynamicEnhancementAgent=false